### ISSUE TITLE
GitHub Contribute links are incorrect

### ISSUE THREAD

**Issue by bjsawyer** [expertly-simple/angularevergreen.com#2]
The GitHub Contribute links on the very bottom of the page (see screenshot below) still route to https://github.com/duluca/angular-evergreen. They should instead route to the new repo location (https://github.com/expertly-simple/angular-evergreen).

![image](https://user-images.githubusercontent.com/8974594/61306693-0bc9ac80-a7bb-11e9-9ab8-609e5a413e6c.png)

**Comment by duluca** [comment]
Fixed
